---
version: 2
plugins:
  duplication:
    enabled: true
    config:
      debug: true
      languages:
        - javascript
exclude_paths:
  - ".idea/"
  - ".git/"
  - ".firebase/"
  - "release/"
  - "assets/"
  - "node_modules/"
  - "config/"
  - "docs/"
  - "projects/"
  - "deploy/"
  - "hooks/"
  - "firebase/"
  - "App_Resources/"
  - "design/"
  - "e2e/"
  - "functions/"
  - "public/"
  - "platforms/"
  - "tools/"
  - "webpack.config.js"
  - "webpack.server.config.js"
  - "src/shared/admin/map/shared/map-list.ts"
  - "src/*.js"
  - "src/**/test.ts"
  - "server.ts"
  - "prerender.ts"
  - "karma.conf.js"
  - "src/**/karma.conf.js"
