---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
exclude_paths:
  - ".github/"
  - "release/"
  - "assets/"
  - "config/"
  - "docs/"
  - "hooks/"
  - "firebase/"
  - "App_Resources/"
  - "design/"
  - "e2e/"
  - "functions/"
  - "public/"
  - "tools/"
  - "webpack.config.js"
  - "webpack.server.config.js"
  - "src/shared/admin/map/shared/map-list.ts"
  - "src/*.js"
  - "src/**/test.ts"
  - "server.ts"
  - "prerender.ts"
ratings:
  paths:
    - "src/**/**.ts"
