dist: trusty
sudo: false
language: node_js
node_js:
  - lts/*
addons:
  apt:
    packages:
      - google-chrome-stable
before_install:
  - npm i -g npm firebase-tools nativescript
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run lint -- --project=showcase
  - npm run test -- --project=showcase
  - npm run build -- --project=showcase
after_success:
  - firebase use showcase --token $FIREBASE_TOKEN
  - firebase deploy --only hosting:aot --token $FIREBASE_TOKEN
branches:
  only:
    - master
notifications:
  slack:
    secure: HBTlDv0fdeax1WntTvbxpyrX+ktoIUKgSZAjOC52Amyrvg0JdYZRXMVEW6y63OneWTMBN5iCZNh7gr02858ozfmazsNLHYsxsH8rUMlR3G6hg2H2oy9KQO37ZI62SmjIUKD6rgD+bvvvbrm1POH+dW4Q3FwR+Xo26YNpo9gsZw/gwG8ulvFIeB/FGGaprJX5C1jGP+UnxMpKkP4qi3LQolsEC0BULX5g4iyoVCYdyJxLqmmDgv01d4+tjAja5GmOm0dFW8p8A8pKQYUm+6JCTYZa52/zxyTxHaJ6o6ERRWHNHP8d6l3Vg2MY9l2nEzWVhXgpYyh9WfsfmQEUBv9f0JPvugU1BwV9C+JzDhB+sWFXrmF6MwaN/WoQoB66Myxy8lerIkb/FwELA9usAI8g6CEDun2it4uERGJO5xA1WL6x+AAfkcOIT/srCEEuPwHwJHtOMpfKjKG7d9DWk7bWVGXiGVDxYv1KF5GKcCx7jkd1vKzwC3J8nKnKi6NK7lE7FgsCZSxi4bGIPC8rZeqv+NWHrJGex29puci7WxaIj75oVWBjtteOabNCFcptEvksVfxpWwqP92dFN+/JXH1HoCNRf9DviVxfqgTXTqdXWyRBXG2NwKkeZbl1rtPAsaOOBr1hUh6qfilcUblAedSY8vgX2kPwTeWIEwSRoPsTOe8=
