export const mockProduct = {
  name: 'Pull moche',
  score: 1,
  created_at: new Date(),
  published_at: new Date(),
  url: 'key',
  description: '',
  thumbnail: '',
  images: [],
  image1: '',
  image2: '',
  image3: '',
  price: 1,
  published: true,
  delivery_fee: 1,
  delivery_free: true,
  reseller: '',
  resellers: ['kjolpm656', 'jx6vff65s6'],
  key: '',
  user: '',
  creator: '',
  external_url: '',
};
