import { Product } from './product';
import * as firebase from 'firebase/app';
import Timestamp = firebase.firestore.Timestamp;

export const mockProduct: Product = {
  name: 'Apple Iphone 8 plus 64Go',
  score: 1,
  created_at: new Date(),
  published_at: Timestamp.now(),
  url: 'key',
  description: '',
  thumbnail: '',
  images: [],
  image1: '',
  image2: '',
  image3: '',
  price: 799,
  published: true,
  delivery_fee: 1,
  delivery_free: true,
  reseller: '',
  offers: ['kjolpm656', 'jx6vff65s6'],
  key: 'sd26s5263sd3',
  user: '',
  creator: '',
  external_url: '',
};

export const mockInvoiceProducts: Product[] = [
  {
    name: 'Apple Iphone 8 plus 64Go',
    score: 1,
    created_at: new Date(),
    published_at: Timestamp.now(),
    url: 'key',
    description: '',
    thumbnail: '',
    images: [],
    image1: '',
    image2: '',
    image3: '',
    price: 799,
    quantity: 2,
    published: true,
    delivery_fee: 1,
    delivery_free: true,
    reseller: '',
    offers: ['kjolpm656', 'jx6vff65s6'],
    key: 's56F656TBFB63265RG989G',
    user: '',
    creator: '',
    external_url: '',
  },
  {
    name: 'Macbook Pro 15" 512Go',
    score: 1,
    created_at: new Date(),
    published_at: Timestamp.now(),
    url: 'key',
    description: '',
    thumbnail: '',
    images: [],
    image1: '',
    image2: '',
    image3: '',
    price: 2399,
    quantity: 1,
    published: true,
    delivery_fee: 1,
    delivery_free: true,
    reseller: '',
    offers: ['kjolpm656', 'jx6vff65s6'],
    key: 'a65F545dD485412REVD',
    user: '',
    creator: '',
    external_url: '',
  }
];
